Algoritmo "SaladaDeFruta"

Var
fruta: Caractere

Inicio

escreval(">>> SUA SALADA DE FRUTA:")

enquanto fruta <> "cereja" faca
         escreva("Qual fruta adicionar? ")
         leia(fruta)
         
         se fruta = "cereja" entao
            escreval()
            escreval("Sua salada de frutas está pronta!")
            
         fimse
         
fimenquanto


Fimalgoritmo