Algoritmo "MEU PRIMEIRO SE SENAO"

Var
nomePessoa: Caractere
idadePessoa: Inteiro

Inicio

escreva("Qual o seu nome? ")
leia(nomePessoa)

escreva("Qual a sua idade? ")
leia(idadePessoa)

escreval()

se (nomePessoa = "Abgail") entao
   escreval("Que tistreza :(")
   
senao
     escreval("Top!! :D")

fimse

se (idadePessoa >= 40) entao
   escreval("Ta ficando veio... :o")

senao
     escreval("Ta novasso... .-.")

fimse

Fimalgoritmo